In [4]:
import numpy as np
import pandas
import matplotlib.pyplot
import seaborn

<span style='color:red'>
단일 넘파이 array는 반드시 단일 sequence를 넣어야함! </br>
np.array([1, 2, 3], [2, 3, 4]) : 틀림</br>
np.array([[1, 2, 3], [2, 3, 4]]) : 맞음</br>
.shape : 차원과 크기를 튜플로 달려줌 -> (row, columns)
</span>

In [6]:
array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1, 2, 3], [2, 3, 4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


<span style='color:red'>
array1 : 1차원의 데이터 3개 </br>
array2 : 2차원의 2row * 3columns</br>
array3 : 2차원의 1행 * 3열
</span>

<span style='color:blue'>
차원의 확인 .ndim </span>

In [10]:
print('array1 : {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))
print(f'array1 : {array1.ndim}차원, array2: {array2.ndim}차원, array3: {array3.ndim}차원')

array1 : 1차원, array2: 2차원, array3: 2차원
array1 : 1차원, array2: 2차원, array3: 2차원


<span style='color:green'>
데이터 타입 확인 .dtype
</span>

In [11]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


<span style='color:green'>
다른 데이터 유형이 섞여있는 리스트를 ndarray로 변환 => 더 큰 데이터 타입으로 일괄 적용
</span>

In [12]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


<span style='color:green'>
.astype() : 타입변환 / 메모리 절약할 때!
</span>

In [13]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


<span style='color:green'>
ndarray 기본으로 생성 - np.arrange(), np.zeros(), np.ones()<br>
    arrange()는 파이썬 기본 arrange()와 사용법 똑같음 <br>
    zeros와 ones는 .shape의 결과의 형태를 적어줘서 만듦
    zeros와 ones의 default dtype이 float64
</span>

In [16]:
sequence_array = np.arange(1, 10, 2)
print(sequence_array, sequence_array.dtype, sequence_array.shape)

zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array, zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2))
print(one_array, one_array.dtype, one_array.shape)

[1 3 5 7 9] int32 (5,)
[[0 0]
 [0 0]
 [0 0]] int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]] float64 (3, 2)


<span style='color:green'>
shape변경 .reshape(row, column)<br>
    전체 크기 안맞게 바꾸면 오류
</span>

In [18]:
array1 = np.arange(10)
print('array1:', array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1: [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [19]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

<span style='color:green'>
-1을 쓰면 알맞는 값으로 알아서 넣음!
    호환되는 값이 없으면 오류남
</span>

In [20]:
array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

array2 shape: (2, 5)
array3 shape: (5, 2)


In [24]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
# tolist()를 이용해 ndarray를 다시 리스트로 변환 가능
print('array3d:\n',array3d.tolist())
print('array3 shape:',array3d.shape)
print('array3 type:',type(array3d))
print('array3 type:',type(array3d.tolist()))


# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array3 shape: (2, 2, 2)
array3 type: <class 'numpy.ndarray'>
array3 type: <class 'list'>
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


<span style='color:blue'>
인덱싱 종류 4가지<br>
1. 단일값 추출<br>
2. 슬라이싱<br>
3. Fancy indexing<br>
4. Boolean indexing
</span>

In [25]:
# 단일값 추출
array1 = np.arange(start=1, stop=10)
# 단일값 수정
array1[6] = 10
print('array1:',array1)

array1: [ 1  2  3  4  5  6 10  8  9]


In [27]:
# 슬라이싱은 익숙하니 아래처럼도 쓸수있다는것만 확인
array1 = np.arange(start=1, stop=10)
array6 = array1[:]
print(array6)

[1 2 3 4 5 6 7 8 9]


In [29]:
#2차원 ndarray의 인덱싱 : [rows인덱싱, columns인덱싱]
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)
print('array2d[1:3, 0:3] :\n', array2d[1:3, 0:3])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[1:3, 0:3] :
 [[4 5 6]
 [7 8 9]]


<span style='color:green'>
Fancy Indexing : 슬라이스의 표기법을 그냥 리스트 표기로 바꾼 것(섞어쓸 수도 있음)<br>
    차이는 인덱스는 범위 a<= x <b' 이지만, list는 'a<= x < b' 거나 a = x임
</span>

In [44]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

print('array2d :\n', array2d)

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] : \n',array3)

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] : \n',array4)

array5 = array2d[[0,1]]
print('array2d[[0,1]] : \n',array5)

array2d :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0,1], 2] : 
 [3 6]
array2d[[0,1], 0:2] : 
 [[1 2]
 [4 5]]
array2d[[0,1]] : 
 [[1 2 3]
 [4 5 6]]


<span style='color:green'>
불린 인덱싱 : []안에 불린 값으로 넣어놓으면 True인 값만 추출<br>
    1. true에 해당하는 인덱스를 추출 -> 2. 인덱스에 해당하는 값을 조회
</span>

In [10]:
array1d = np.arange(start=1, stop=10)
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]
print('일반 인덱스로 필터링 결과 :',array4)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]
일반 인덱스로 필터링 결과 : [6 7 8 9]


In [11]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

<span style='color:green'>
1) np.sort() : 넘파이 메서드 호출, 원행렬을 유지한채 정렬한 행렬을 반환<br>
2) ndarray.sort() : 행렬자체 메서드 호출, 원행렬 자체를 정렬해서 반환
</span>

In [12]:
org_array = np.array([ 3, 1, 9, 5]) 
print('원본 행렬:', org_array)

sort_array1 = np.sort(org_array)         
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) 
print('np.sort( ) 호출 후 원본 행렬:', org_array)

sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


<span style='color:green'>
정렬은 기본이 오름차순 // 내림차순은 [::-1]을 뒤에 붙임
</span>

In [13]:
sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc) 

내림차순으로 정렬: [9 5 3 1]


<span style='color:green'>
2차원 이상일 경우, y축(로우방향) 정렬:axis=0, x축(컬럼방향) 정렬:axis=1, [::-1]은 공통
</span>

In [14]:
array2d = np.array([[8, 12], 
                   [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


<span style='color:green'>
np.argsort(리스트) 동작 순서 : 1) 원본 행렬 인덱스를 추적 2) 정렬된 상태의 인덱스를 ndarray로 추출
</span>

In [15]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


<span style='color:red'>
numpy의 ndarray만 메타 데이터를 가질 수 없음.<br>
    즉, 일반적으로 데이터값과 메타데이터의 2개의 ndarray를 만들어야함<br>
    만약 값의 순서에 따른 메타데이터를 출력하고 자 한다면<br>
1) 값의 ndarray의 np.argsort() 이후<br>
2) 해당 인덱스로 메타데이터의 ndarray 출력
</span>

In [17]:
name_array = np.array(['우석', '현지', '준호'])
score_array = np.array(['78', '95', '84'])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 1]
성적 오름차순으로 name_array의 이름 출력: ['우석' '준호' '현지']


<span style='color:red'>
행렬 내적 np.dot(A, B) // 2*3 (내적) 3*2 = 2*2 행<br>
    - 데이터 변환: 행렬 곱셈은 데이터를 다른 형태로 변환하는 데 사용됩니다.<br> 예를 들어, 이미지 처리에서 이미지를 회전하거나 확대/축소할 때 행렬 곱셈이 사용됩니다.<br>
전치 행렬 A -> A^T // np.transpose(A) // 왼쪽위 잡고 180도 돌리기<br>
 - 1) (AT)T = A   2) (kA)T = kAT   3) (A+B)T = AT + BT   4) (AB)T = BTAT

In [5]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]
A의 전치 행렬:
 [[1 3]
 [2 4]]
